Refreshed content for the following images: * centos6.devtoolset-3 * centos6.devtoolset-3-dyninst * centos6.devtoolset-3-eclipse * centos6.devtoolset-3-elfutils * centos6.devtoolset-3-oprofile * centos6.devtoolset-3-systemtap * centos6.devtoolset-3-toolchain * centos6.devtoolset-3-valgrind * centos6.devtoolset-4 * centos6.devtoolset-4-dyninst * centos6.devtoolset-4-elfutils * centos6.devtoolset-4-oprofile * centos6.devtoolset-4-systemtap * centos6.devtoolset-4-toolchain * centos6.devtoolset-4-valgrind * centos7.devtoolset-3 * centos7.devtoolset-3-dyninst * centos7.devtoolset-3-eclipse * centos7.devtoolset-3-elfutils * centos7.devtoolset-3-oprofile * centos7.devtoolset-3-systemtap * centos7.devtoolset-3-toolchain * centos7.devtoolset-3-valgrind * centos7.devtoolset-4 * centos7.devtoolset-4-dyninst * centos7.devtoolset-4-elfutils * centos7.devtoolset-4-oprofile * centos7.devtoolset-4-systemtap * centos7.devtoolset-4-toolchain * centos7.devtoolset-4-valgrind * rhel6.devtoolset-3 * rhel6.devtoolset-3-dyninst * rhel6.devtoolset-3-eclipse * rhel6.devtoolset-3-elfutils * rhel6.devtoolset-3-oprofile * rhel6.devtoolset-3-systemtap * rhel6.devtoolset-3-toolchain * rhel6.devtoolset-3-valgrind * rhel6.devtoolset-4 * rhel6.devtoolset-4-dyninst * rhel6.devtoolset-4-elfutils * rhel6.devtoolset-4-oprofile * rhel6.devtoolset-4-systemtap * rhel6.devtoolset-4-toolchain * rhel6.devtoolset-4-valgrind * rhel7.devtoolset-3 * rhel7.devtoolset-3-dyninst * rhel7.devtoolset-3-eclipse * rhel7.devtoolset-3-elfutils * rhel7.devtoolset-3-oprofile * rhel7.devtoolset-3-systemtap * rhel7.devtoolset-3-toolchain * rhel7.devtoolset-3-valgrind * rhel7.devtoolset-4 * rhel7.devtoolset-4-dyninst * rhel7.devtoolset-4-elfutils * rhel7.devtoolset-4-oprofile * rhel7.devtoolset-4-systemtap * rhel7.devtoolset-4-toolchain * rhel7.devtoolset-4-valgrind * centos7.mysql55 * rhel7.mysql55 * centos7.rh-mysql56 * centos7.postgresql92 * rhel7.postgresql92 * centos7.rh-postgresql94 * centos7.mongodb24 * rhel7.mongodb24 * centos7.rh-mongodb26 * centos7.rh-python34 * centos7.python33 * rhel7.python33 * centos7.python27 * centos7.perl516 * rhel7.perl516 * centos7.rh-perl520 * centos7.ruby20 * rhel7.ruby20 * centos7.rh-ruby22 * centos7.nodejs010 * centos7.php55 * rhel7.php55 * centos7.rh-php56

diff --git a/centos7.rh-mongodb26/test/run b/centos7.rh-mongodb26/test/run
--- a/centos7.rh-mongodb26/test/run
+++ b/centos7.rh-mongodb26/test/run
@@ -142,6 +142,26 @@ function create_container() {
     echo "Created container $(cat $cidfile)"
 }
 
+function assert_login_access() {
+    local USER=$1 ; shift
+    local PASS=$1 ; shift
+    local success=$1 ; shift
+
+    if mongo_cmd 'db.version()' ; then
+        if $success ; then
+            echo "    $USER($PASS) access granted as expected"
+            return
+        fi
+    else
+        if ! $success ; then
+            echo "    $USER($PASS) access denied as expected"
+            return
+        fi
+    fi
+    echo "    $USER($PASS) login assertion failed"
+    exit 1
+}
+
 function run_tests() {
     local name=$1 ; shift
     envs="-e MONGODB_USER=$USER -e MONGODB_PASSWORD=$PASS -e MONGODB_DATABASE=$DB"
@@ -157,8 +177,78 @@ function run_tests() {
     mongo_cmd_local $name <<< ""
 }
 
+function run_change_password_test() {
+    local name="change_password"
+
+    local database='db'
+    local user='user'
+    local password='password'
+    local admin_password='adminPassword'
+
+    local volume_dir
+    volume_dir=`mktemp -d --tmpdir mongodb-testdata.XXXXX`
+    chmod a+rwx ${volume_dir}
+
+    DOCKER_ARGS="
+-e MONGODB_DATABASE=${database}
+-e MONGODB_USER=${user}
+-e MONGODB_PASSWORD=${password}
+-e MONGODB_ADMIN_PASSWORD=${admin_password}
+-v ${volume_dir}:/var/lib/mongodb/data
+"
+    create_container ${name} ${DOCKER_ARGS}
+
+    # need to set these because `mongo_cmd` relies on global variables
+    USER=${user}
+    PASS=${password}
+    DB=${database}
+
+    # need this to wait for the container to start up
+    CONTAINER_IP=$(get_container_ip ${name})
+    test_connection ${name}
+
+    echo "  Testing login"
+
+    assert_login_access ${user} ${password} true
+    DB='admin' assert_login_access 'admin' ${admin_password} true
+
+    echo "  Changing passwords"
+
+    docker stop $(get_cid ${name})
+    DOCKER_ARGS="
+-e MONGODB_DATABASE=${database}
+-e MONGODB_USER=${user}
+-e MONGODB_PASSWORD=NEW_${password}
+-e MONGODB_ADMIN_PASSWORD=NEW_${admin_password}
+-v ${volume_dir}:/var/lib/mongodb/data
+"
+    create_container "${name}_NEW" ${DOCKER_ARGS}
+
+    # need to set this because `mongo_cmd` relies on global variables
+    PASS="NEW_${password}"
+
+    # need this to wait for the container to start up
+    CONTAINER_IP=$(get_container_ip "${name}_NEW")
+    test_connection "${name}_NEW"
+
+    echo "  Testing login with new passwords"
+
+    assert_login_access ${user} "NEW_${password}" true
+    assert_login_access ${user} ${password} false
+
+    DB='admin' assert_login_access 'admin' "NEW_${admin_password}" true
+    DB='admin' assert_login_access 'admin' ${admin_password} false
+
+    # need to remove volume_dir with sudo because of permissions of files written
+    # by the Docker container
+    sudo rm -rf ${volume_dir}
+
+    echo "  Success!"
+}
+
 # Tests.
 run_configuration_tests
 USER="user1" PASS="pass1" DB="test_db" ADMIN_PASS="r00t" run_tests admin
 # Test with random uid in container
 CONTAINER_ARGS="-u 12345" USER="user1" PASS="pass1" DB="test_db" ADMIN_PASS="r00t" run_tests admin_altuid
+run_change_password_test
