Refreshed content for the following images: * rhel7.devtoolset-4-perftools * rhel7.devtoolset-4-toolchain * rhel7.httpd24 * rhel7.nginx16 * rhel7.python27 * rhel7.rh-mariadb100 * rhel7.rh-mariadb101 * rhel7.rh-mongodb26 * rhel7.rh-mongodb32 * rhel7.rh-mysql56 * rhel7.rh-nginx18 * rhel7.rh-nodejs4 * rhel7.rh-passenger40 * rhel7.rh-perl520 * rhel7.rh-php56 * rhel7.rh-postgresql94 * rhel7.rh-postgresql95 * rhel7.rh-python34 * rhel7.rh-python35 * rhel7.rh-ror41 * rhel7.rh-ror42 * rhel7.rh-ruby22 * rhel7.rh-ruby23 * rhel7.rh-varnish4 * rhel7.s2i-base * rhel7.thermostat1-agent * rhel7.mysql55 * rhel7.postgresql92 * rhel7.mongodb24 * rhel7.nodejs010 * rhel7.perl516 * rhel7.php55 * rhel7.python33 * rhel7.ruby20 * rhel7.sti-base

diff --git a/rhel7.rh-mysql56/test/run b/rhel7.rh-mysql56/test/run
--- a/rhel7.rh-mysql56/test/run
+++ b/rhel7.rh-mysql56/test/run
@@ -6,25 +6,31 @@
 # The image has to be available before this script is executed.
 #
 
-set -exo nounset
+set -o errexit
+set -o nounset
 shopt -s nullglob
 
-IMAGE_NAME=${IMAGE_NAME-centos/mysql-56-centos7-candidate}
+IMAGE_NAME=${IMAGE_NAME-openshift/mysql-56-centos7-candidate}
 
 CIDFILE_DIR=$(mktemp --suffix=mysql_test_cidfiles -d)
 
 function cleanup() {
+  local cidfile
   for cidfile in $CIDFILE_DIR/* ; do
+    local CONTAINER
     CONTAINER=$(cat $cidfile)
 
     echo "Stopping and removing container $CONTAINER..."
-    docker stop $CONTAINER
+    docker stop $CONTAINER >/dev/null
+    local exit_status
     exit_status=$(docker inspect -f '{{.State.ExitCode}}' $CONTAINER)
     if [ "$exit_status" != "0" ]; then
+      echo "Inspecting container $CONTAINER"
+      docker inspect $CONTAINER
       echo "Dumping logs for $CONTAINER"
       docker logs $CONTAINER
     fi
-    docker rm $CONTAINER
+    docker rm -v $CONTAINER >/dev/null
     rm $cidfile
     echo "Done."
   done
@@ -43,22 +49,25 @@ function get_container_ip() {
 }
 
 function mysql_cmd() {
-  docker run --rm $IMAGE_NAME mysql --host $CONTAINER_IP -u$USER -p"$PASS" "$@" db
+  local container_ip="$1"; shift
+  local login="$1"; shift
+  local password="$1"; shift
+  docker run --rm "$IMAGE_NAME" mysql --host "$container_ip" -u"$login" -p"$password" "$@" db
 }
 
 function test_connection() {
   local name=$1 ; shift
+  local login=$1 ; shift
+  local password=$1 ; shift
+  local ip
   ip=$(get_container_ip $name)
   echo "  Testing MySQL connection to $ip..."
   local max_attempts=20
   local sleep_time=2
+  local i
   for i in $(seq $max_attempts); do
     echo "    Trying to connect..."
-    set +e
-    mysql_cmd <<< "SELECT 1;"
-    status=$?
-    set -e
-    if [ $status -eq 0 ]; then
+    if mysql_cmd "$ip" "$login" "$password" <<< 'SELECT 1;'; then
       echo "  Success!"
       return 0
     fi
@@ -70,13 +79,17 @@ function test_connection() {
 }
 
 function test_mysql() {
+  local container_ip="$1"
+  local login="$2"
+  local password="$3"
+
   echo "  Testing MySQL"
-  mysql_cmd <<< "CREATE TABLE tbl (col1 VARCHAR(20), col2 VARCHAR(20));"
-  mysql_cmd <<< "INSERT INTO tbl VALUES ('foo1', 'bar1');"
-  mysql_cmd <<< "INSERT INTO tbl VALUES ('foo2', 'bar2');"
-  mysql_cmd <<< "INSERT INTO tbl VALUES ('foo3', 'bar3');"
-  mysql_cmd <<< "SELECT * FROM tbl;"
-  mysql_cmd <<< "DROP TABLE tbl;"
+  mysql_cmd "$container_ip" "$login" "$password" <<< 'CREATE TABLE tbl (col1 VARCHAR(20), col2 VARCHAR(20));'
+  mysql_cmd "$container_ip" "$login" "$password" <<< 'INSERT INTO tbl VALUES ("foo1", "bar1");'
+  mysql_cmd "$container_ip" "$login" "$password" <<< 'INSERT INTO tbl VALUES ("foo2", "bar2");'
+  mysql_cmd "$container_ip" "$login" "$password" <<< 'INSERT INTO tbl VALUES ("foo3", "bar3");'
+  mysql_cmd "$container_ip" "$login" "$password" <<< 'SELECT * FROM tbl;'
+  mysql_cmd "$container_ip" "$login" "$password" <<< 'DROP TABLE tbl;'
   echo "  Success!"
 }
 
@@ -84,8 +97,9 @@ function create_container() {
   local name=$1 ; shift
   cidfile="$CIDFILE_DIR/$name"
   # create container with a cidfile in a directory for cleanup
-  docker run ${DOCKER_ARGS:-} --cidfile $cidfile -d "$@" $IMAGE_NAME ${CONTAINER_ARGS:-}
-  echo "Created container $(cat $cidfile)"
+  local container_id
+  container_id="$(docker run ${DOCKER_ARGS:-} --cidfile $cidfile -d "$@" $IMAGE_NAME ${CONTAINER_ARGS:-})"
+  echo "Created container $container_id"
 }
 
 function run_change_password_test() {
@@ -95,19 +109,18 @@ function run_change_password_test() {
   # Create MySQL container with persistent volume and set the initial password
   create_container "testpass1" -e MYSQL_USER=user -e MYSQL_PASSWORD=foo \
     -e MYSQL_DATABASE=db -v ${tmpdir}:/var/lib/mysql/data:Z
-  CONTAINER_IP=$(get_container_ip testpass1) USER=user PASS=foo test_connection "testpass1"
-  docker stop $(get_cid testpass1)
+  test_connection testpass1 user foo
+  docker stop $(get_cid testpass1) >/dev/null
 
   # Create second container with changed password
   create_container "testpass2" -e MYSQL_USER=user -e MYSQL_PASSWORD=bar \
     -e MYSQL_DATABASE=db -v ${tmpdir}:/var/lib/mysql/data:Z
-  CONTAINER_IP=$(get_container_ip testpass2) USER=user PASS=bar test_connection "testpass2"
+  test_connection testpass2 user bar
 
   # The old password should not work anymore
-  set +e
-  CONTAINER_IP=$(get_container_ip testpass2) USER=user PASS=foo \
-    mysql_cmd -e "SELECT 1;" && return 1
-  set -e
+  if mysql_cmd "$(get_container_ip testpass2)" user foo -e 'SELECT 1;'; then
+    return 1
+  fi
 }
 
 function run_replication_test() {
@@ -117,23 +130,23 @@ function run_replication_test() {
   # Run the MySQL master
   docker run $cluster_args -e MYSQL_USER=user -e MYSQL_PASSWORD=foo \
     -e MYSQL_ROOT_PASSWORD=root \
-    -d --cidfile ${CIDFILE_DIR}/master.cid $IMAGE_NAME mysqld-master \
-    --innodb_buffer_pool_size=5242880
+    -e MYSQL_INNODB_BUFFER_POOL_SIZE=5M \
+    -d --cidfile ${CIDFILE_DIR}/master.cid $IMAGE_NAME mysqld-master >/dev/null
+  local master_ip
   master_ip=$(get_container_ip master.cid)
 
   # Run the MySQL slave
   docker run $cluster_args -e MYSQL_MASTER_SERVICE_NAME=${master_ip} \
-    -d --cidfile ${CIDFILE_DIR}/slave.cid $IMAGE_NAME mysqld-slave \
-    --innodb_buffer_pool_size=5242880
+    -e MYSQL_INNODB_BUFFER_POOL_SIZE=5M \
+    -d --cidfile ${CIDFILE_DIR}/slave.cid $IMAGE_NAME mysqld-slave >/dev/null
+  local slave_ip
   slave_ip=$(get_container_ip slave.cid)
 
   # Now wait till the MASTER will see the SLAVE
+  local i
   for i in $(seq $max_attempts); do
-    set +e
-    result=$(CONTAINER_IP=${master_ip} USER=root PASS=root \
-      mysql_cmd -e "SHOW SLAVE HOSTS;" | grep ${slave_ip})
-    set -e
-    if [[ ! -z "${result}" ]]; then
+    result="$(mysql_cmd "$master_ip" root root -e 'SHOW SLAVE HOSTS;' | grep "$slave_ip" || true)"
+    if [[ -n "${result}" ]]; then
       echo "${slave_ip} successfully registered as SLAVE for ${master_ip}"
       break
     fi
@@ -145,37 +158,15 @@ function run_replication_test() {
     fi
     sleep 1
   done
-
-  # do some real work to test replication in practice
-  CONTAINER_IP=${master_ip} USER=root PASS=root \
-    mysql_cmd -e "CREATE TABLE t1 (a INT); INSERT INTO t1 VALUES (24);"
-
-  # read value from slave and check whether it is expectd
-  for i in $(seq $max_attempts); do
-    set +e
-    result=$(CONTAINER_IP=${slave_ip} USER=root PASS=root \
-      mysql_cmd -e "select * from t1 \G" | grep -e ^a | grep 24)
-    set -e
-    if [[ ! -z "${result}" ]]; then
-      echo "${slave_ip} successfully got value from MASTER ${master_ip}"
-      break
-    fi
-    if [[ "${i}" == "${max_attempts}" ]]; then
-      echo "The ${slave_ip} failed to see value added on MASTER"
-      echo "Dumping logs for $(get_cid slave.cid)"
-      docker logs $(get_cid slave.cid)
-      return 1
-    fi
-    sleep 1
-  done
 }
 
 function assert_login_access() {
+  local container_ip=$1; shift
   local USER=$1 ; shift
   local PASS=$1 ; shift
   local success=$1 ; shift
 
-  if mysql_cmd <<<'SELECT 1;' ; then
+  if mysql_cmd "$container_ip" "$USER" "$PASS" <<< 'SELECT 1;' ; then
     if $success ; then
       echo "    $USER($PASS) access granted as expected"
       return
@@ -201,10 +192,8 @@ function assert_container_creation_fails() {
   # Time the docker run command. It should fail. If it doesn't fail,
   # mysqld will keep running so we kill it with SIGKILL to make sure
   # timeout returns a non-zero value.
-  set +e
-  timeout -s 9 --preserve-status 60s docker run --rm "$@" $IMAGE_NAME
-  ret=$?
-  set -e
+  local ret=0
+  timeout -s 9 --preserve-status 60s docker run --rm "$@" $IMAGE_NAME >/dev/null || ret=$?
 
   # Timeout will exit with a high number.
   if [ $ret -gt 30 ]; then
@@ -213,7 +202,6 @@ function assert_container_creation_fails() {
 }
 
 function try_image_invalid_combinations() {
-  assert_container_creation_fails -e MYSQL_USER=user -e MYSQL_PASSWORD=pass "$@"
   assert_container_creation_fails -e MYSQL_USER=user -e MYSQL_DATABASE=db "$@"
   assert_container_creation_fails -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db "$@"
 }
@@ -224,32 +212,109 @@ function run_container_creation_tests() {
   try_image_invalid_combinations
   try_image_invalid_combinations  -e MYSQL_ROOT_PASSWORD=root_pass
 
-  VERY_LONG_DB_NAME="very_long_database_name_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
+  local VERY_LONG_DB_NAME="very_long_database_name_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
+  assert_container_creation_fails -e MYSQL_USER=user -e MYSQL_PASSWORD=pass
   assert_container_creation_fails -e MYSQL_USER=\$invalid -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -e MYSQL_ROOT_PASSWORD=root_pass
   assert_container_creation_fails -e MYSQL_USER=very_long_username -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -e MYSQL_ROOT_PASSWORD=root_pass
   assert_container_creation_fails -e MYSQL_USER=user -e MYSQL_PASSWORD="\"" -e MYSQL_DATABASE=db -e MYSQL_ROOT_PASSWORD=root_pass
   assert_container_creation_fails -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=\$invalid -e MYSQL_ROOT_PASSWORD=root_pass
   assert_container_creation_fails -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=$VERY_LONG_DB_NAME -e MYSQL_ROOT_PASSWORD=root_pass
   assert_container_creation_fails -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -e MYSQL_ROOT_PASSWORD="\""
+  assert_container_creation_fails -e MYSQL_USER=root -e MYSQL_PASSWORD=pass -e MYSQL_DATABASE=db -e MYSQL_ROOT_PASSWORD=pass
   echo "  Success!"
 }
 
 function test_config_option() {
-  local env_var=$1 ; shift
-  local setting=$1 ; shift
-  local value=$1 ; shift
+  local container_name="$1"
+  local configuration="$2"
+  local option_name="$3"
+  local option_value="$4"
 
-  # If $value is a string, it needs to be in simple quotes ''.
-  # If nothing is found, grep returns 1 and test fails.
-  docker run --rm -e $env_var=${value//\'/} $IMAGE_NAME cat /var/lib/mysql/my.cnf | grep -q "$setting = $value"
+  if ! echo "$configuration" | grep -qx "$option_name[[:space:]]*=[[:space:]]*$option_value"; then
+    local configs="$(docker exec -t "$container_name" bash -c 'set +f; shopt -s nullglob; echo /etc/my.cnf /etc/my.cnf.d/* /opt/rh/mysql*/root/etc/my.cnf /opt/rh/mysql*/root/etc/my.cnf.d/* | paste -s')"
+    echo >&2 "FAIL: option '$option_name' should have value '$option_value', but it wasn't found in any of the configuration files ($configs):"
+    echo >&2
+    echo >&2 "$configuration"
+    echo >&2
+    return 1
+  fi
+
+  return 0
 }
 
 function run_configuration_tests() {
   echo "  Testing image configuration settings"
-  test_config_option MYSQL_LOWER_CASE_TABLE_NAMES lower_case_table_names 1
-  test_config_option MYSQL_MAX_CONNECTIONS max_connections 1337
-  test_config_option MYSQL_FT_MIN_WORD_LEN ft_min_word_len 8
-  test_config_option MYSQL_FT_MAX_WORD_LEN ft_max_word_len 15
+
+  local container_name=config_test
+
+  create_container \
+    "$container_name" \
+    --name "$container_name" \
+    --env MYSQL_USER=config_test_user \
+    --env MYSQL_PASSWORD=config_test \
+    --env MYSQL_DATABASE=db \
+    --env MYSQL_LOWER_CASE_TABLE_NAMES=1 \
+    --env MYSQL_MAX_CONNECTIONS=1337 \
+    --env MYSQL_FT_MIN_WORD_LEN=8 \
+    --env MYSQL_FT_MAX_WORD_LEN=15 \
+    --env MYSQL_MAX_ALLOWED_PACKET=10M \
+    --env MYSQL_TABLE_OPEN_CACHE=100 \
+    --env MYSQL_SORT_BUFFER_SIZE=256K \
+    --env MYSQL_KEY_BUFFER_SIZE=16M \
+    --env MYSQL_READ_BUFFER_SIZE=16M \
+    --env MYSQL_INNODB_BUFFER_POOL_SIZE=16M \
+    --env MYSQL_INNODB_LOG_FILE_SIZE=4M \
+    --env MYSQL_INNODB_LOG_BUFFER_SIZE=4M \
+    --env WORKAROUND_DOCKER_BUG_14203=
+    #
+
+  test_connection "$container_name" config_test_user config_test
+
+  # TODO: this check is far from perfect and could be improved:
+  # - we should look for an option in the desired config, not in all of them
+  # - we should respect section of the config (now we have duplicated options from a different sections)
+  local configuration
+  configuration="$(docker exec -t "$container_name" bash -c 'set +f; shopt -s nullglob; egrep -hv "^(#|\!|\[|$)" /etc/my.cnf /etc/my.cnf.d/* /opt/rh/mysql*/root/etc/my.cnf /opt/rh/mysql*/root/etc/my.cnf.d/*' | sed 's,\(^[[:space:]]\+\|[[:space:]]\+$\),,' | sort -u)"
+
+  test_config_option "$container_name" "$configuration" lower_case_table_names 1
+  test_config_option "$container_name" "$configuration" max_connections 1337
+  test_config_option "$container_name" "$configuration" ft_min_word_len 8
+  test_config_option "$container_name" "$configuration" ft_max_word_len 15
+  test_config_option "$container_name" "$configuration" max_allowed_packet 10M
+  test_config_option "$container_name" "$configuration" table_open_cache 100
+  test_config_option "$container_name" "$configuration" sort_buffer_size 256K
+  test_config_option "$container_name" "$configuration" key_buffer_size 16M
+  test_config_option "$container_name" "$configuration" read_buffer_size 16M
+  test_config_option "$container_name" "$configuration" innodb_buffer_pool_size 16M
+  test_config_option "$container_name" "$configuration" innodb_log_file_size 4M
+  test_config_option "$container_name" "$configuration" innodb_log_buffer_size 4M
+
+  docker stop "$container_name" >/dev/null
+
+  echo "  Success!"
+  echo "  Testing image auto-calculated configuration settings"
+
+  container_name=dynamic_config_test
+
+  DOCKER_ARGS='--memory=256m' create_container \
+    "$container_name" \
+    --name "$container_name" \
+    --env MYSQL_USER=config_test_user \
+    --env MYSQL_PASSWORD=config_test \
+    --env MYSQL_DATABASE=db
+
+  test_connection "$container_name" config_test_user config_test
+
+  configuration="$(docker exec -t "$container_name" bash -c 'set +f; shopt -s nullglob; egrep -hv "^(#|\!|\[|$)" /etc/my.cnf /etc/my.cnf.d/* /opt/rh/mysql*/root/etc/my.cnf /opt/rh/mysql*/root/etc/my.cnf.d/*' | sed 's,\(^[[:space:]]\+\|[[:space:]]\+$\),,' | sort -u)"
+
+  test_config_option "$container_name" "$configuration" key_buffer_size 25M
+  test_config_option "$container_name" "$configuration" read_buffer_size 12M
+  test_config_option "$container_name" "$configuration" innodb_buffer_pool_size 128M
+  test_config_option "$container_name" "$configuration" innodb_log_file_size 38M
+  test_config_option "$container_name" "$configuration" innodb_log_buffer_size 38M
+
+  docker stop "$container_name" >/dev/null
+
   echo "  Success!"
 }
 
@@ -259,6 +324,7 @@ test_scl_usage() {
   local expected="$3"
 
   echo "  Testing the image SCL enable"
+  local out
   out=$(docker run --rm ${IMAGE_NAME} /bin/bash -c "${run_cmd}")
   if ! echo "${out}" | grep -q "${expected}"; then
     echo "ERROR[/bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
@@ -283,33 +349,31 @@ function run_tests() {
     envs="$envs -e MYSQL_ROOT_PASSWORD=$ROOT_PASS"
   fi
   create_container $name $envs
-  CONTAINER_IP=$(get_container_ip $name)
-  test_connection $name
+  test_connection "$name" "$USER" "$PASS"
   echo "  Testing scl usage"
   test_scl_usage $name 'mysql --version' '5.6'
   echo "  Testing login accesses"
-  assert_login_access $USER $PASS true
-  assert_login_access $USER "${PASS}_foo" false
+  local container_ip
+  container_ip=$(get_container_ip $name)
+  assert_login_access "$container_ip" "$USER" "$PASS" true
+  assert_login_access "$container_ip" "$USER" "${PASS}_foo" false
   if [ -v ROOT_PASS ]; then
-    assert_login_access root $ROOT_PASS true
-    assert_login_access root "${ROOT_PASS}_foo" false
+    assert_login_access "$container_ip" root "$ROOT_PASS" true
+    assert_login_access "$container_ip" root "${ROOT_PASS}_foo" false
   else
-    assert_login_access root "foo" false
-    assert_login_access root "" false
+    assert_login_access "$container_ip" root 'foo' false
+    assert_login_access "$container_ip" root '' false
   fi
-  assert_local_access $name
+  assert_local_access "$name"
   echo "  Success!"
-  test_mysql $name
+  test_mysql "$container_ip" "$USER" "$PASS"
 }
 
 # Tests.
 
 run_container_creation_tests
 
-# FIXME: Disabled because the configuration files are not processed when running
-#        commands like 'cat'. To have the my.cnf processed you have to run one of the
-#        valid entrypoints.
-# run_configuration_tests
+run_configuration_tests
 
 # Set lower buffer pool size to avoid running out of memory.
 export CONTAINER_ARGS="run-mysqld --innodb_buffer_pool_size=5242880"
diff --git a/rhel7.rh-perl520/test/run b/rhel7.rh-perl520/test/run
--- a/rhel7.rh-perl520/test/run
+++ b/rhel7.rh-perl520/test/run
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # The 'run' performs a simple test that verifies that S2I image.
-# The main focus here is to excersise the S2I scripts.
+# The main focus here is to exercise the S2I scripts.
 #
 # IMAGE_NAME specifies a name of the candidate image used for testing.
 # The image has to be available before this script is executed.
@@ -32,7 +32,7 @@ container_ip() {
 }
 
 run_s2i_build() {
-  s2i build ${s2i_args} file://${test_dir}/sample-test-app ${IMAGE_NAME} ${IMAGE_NAME}-testapp
+  s2i build "$@" file://${test_dir}/${test_name} ${IMAGE_NAME} ${IMAGE_NAME}-testapp
 }
 
 prepare() {
@@ -43,7 +43,7 @@ prepare() {
   # TODO: S2I build require the application is a valid 'GIT' repository, we
   # should remove this restriction in the future when a file:// is used.
   info "Build the test application image"
-  pushd ${test_dir}/sample-test-app >/dev/null
+  pushd ${test_dir}/${test_name} >/dev/null
   git init
   git config user.email "build@localhost" && git config user.name "builder"
   git add -A && git commit -m "Sample commit"
@@ -70,7 +70,7 @@ cleanup() {
   if image_exists ${IMAGE_NAME}-testapp; then
     docker rmi -f ${IMAGE_NAME}-testapp
   fi
-  rm -rf ${test_dir}/sample-test-app/.git
+  rm -rf ${test_dir}/${test_name}/.git
 }
 
 check_result() {
@@ -115,21 +115,6 @@ test_scl_usage() {
     echo "ERROR[/bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
     return 1
   fi
-  # out=$(docker run --rm -i ${IMAGE_NAME} /bin/bash -i <<< "${run_cmd}")
-  # if ! echo "${out}" | grep -q "${expected}"; then
-  #   echo "ERROR[-i /bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
-  #   return 1
-  # fi
-  # out=$(docker run --rm -i ${IMAGE_NAME} /bin/bash -l <<< "${run_cmd}")
-  # if ! echo "${out}" | grep -q "${expected}"; then
-  #   echo "ERROR[-i /bin/bash -l "${run_cmd}"] Expected '${expected}', got '${out}'"
-  #   return 1
-  # fi
-  # out=$(docker run --rm -i ${IMAGE_NAME} /bin/sh -ic "${run_cmd}")
-  # if ! echo "${out}" | grep -q "${expected}"; then
-  #   echo "ERROR[/bin/sh -c "${run_cmd}"] Expected '${expected}', got '${out}'"
-  #   return 1
-  # fi
   out=$(docker exec $(cat ${cid_file}) /bin/bash -c "${run_cmd}" 2>&1)
   if ! echo "${out}" | grep -q "${expected}"; then
     echo "ERROR[exec /bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
@@ -142,25 +127,61 @@ test_scl_usage() {
   fi
 }
 
-test_connection() {
-  info "Testing the HTTP connection (http://$(container_ip):${test_port})"
+# Perform GET request to the application container.
+# First argument is request URI path.
+# Second argument is expected HTTP response code.
+# Third argument is PCRE regular expression that must match the response body.
+test_response() {
+  local uri_path="$1"
+  local expected_code="$2"
+  local body_regexp="$3"
+
+  local url="http://$(container_ip):${test_port}${uri_path}"
+  info "Testing the HTTP response for <${url}>"
   local max_attempts=10
   local sleep_time=1
   local attempt=1
   local result=1
   while [ $attempt -le $max_attempts ]; do
-    response_code=$(curl -s -w %{http_code} -o /dev/null http://$(container_ip):${test_port}/)
+    response=$(curl -s -w '%{http_code}' "${url}")
     status=$?
     if [ $status -eq 0 ]; then
-      if [ $response_code -eq 200 ]; then
+      response_code=$(printf '%s' "$response" | tail -c 3)
+      response_body=$(printf '%s' "$response" | head -c -3)
+      if [ "$response_code" -eq "$expected_code" ]; then
         result=0
       fi
+      printf '%s' "$response_body" | grep -qP -e "$body_regexp" || result=1;
       break
     fi
     attempt=$(( $attempt + 1 ))
     sleep $sleep_time
   done
   return $result
+}
+
+# Match PCRE regular expression against container standard output.
+# First argument is the PCRE regular expression.
+# It expects standard output in ${tmp_dir}/out file.
+test_stdout() {
+  local regexp="$1"
+  local output="${tmp_dir}/out"
+  info "Testing the container standard output for /${regexp}/"
+  grep -qP -e "$regexp" "$output";
+}
+
+# Match PCRE regular expression against container standard error output.
+# First argument is the PCRE regular expression.
+# It expects error output in ${tmp_dir}/err file.
+test_stderr() {
+  local regexp="$1"
+  local output="${tmp_dir}/err"
+  info "Testing the container error output for /${regexp}/"
+  grep -qP -e "$regexp" "$output";
+}
+
+test_connection() {
+    test_response '/' 200 ''
 }
 
 test_application() {
@@ -178,31 +199,109 @@ test_application() {
   cleanup_test_app
 }
 
-cid_file=$(mktemp -u --suffix=.cid)
+# Build application, run it, perform test function, clean up.
+# First argument is directory name.
+# Second argument is function that expects running application. The function
+# must return (or terminate with) non-zero value to report an failure,
+# 0 otherwise.
+# Third argument is s2i --env argument value.
+# The test function have available container ID in $cid_file, container output
+# in ${tmp_dir}/out, container stderr in ${tmp_dir}/err.
+do_test() {
+    test_name="$1"
+    test_function="$2"
+    test_environment="$3"
 
-# Since we built the candidate image locally, we don't want S2I attempt to pull
-# it from Docker hub
-s2i_args="--force-pull=false"
+    info "Starting tests for ${test_name}."
 
-prepare
-run_s2i_build
-check_result $?
+    tmp_dir=$(mktemp -d)
+    check_result $?
+    cid_file="${tmp_dir}/cid"
+    s2i_args="--force-pull=false"
 
-# Verify the 'usage' script is working properly when running the base image with 's2i usage ...'
-test_s2i_usage
-check_result $?
+    # Build and run the test application
+    prepare
+    run_s2i_build $s2i_args --env="$test_environment"
+    check_result $?
+    run_test_application >"${tmp_dir}/out" 2>"${tmp_dir}/err" &
+    wait_for_cid
 
-# Verify the 'usage' script is working properly when running the base image with 'docker run ...'
-test_docker_run_usage
-check_result $?
+    # Perform user-supplied test function
+    $test_function;
+    check_result $?
 
-# Test application with default uid
-test_application
+    # Terminate the test application and clean up
+    cleanup_test_app
+    cleanup
+    rm -rf "$tmp_dir"
+    info "All tests for the ${test_name} finished successfully."
+}
 
-# Test application with random uid
-CONTAINER_ARGS="-u 12345" test_application
 
-info "All tests for the sample-test-app finished successfully."
-cleanup
+# List of tests to execute:
+
+# This is original test that does more things like s2i API checks. Other tests
+# executed by do_test() will not repeat these checks.
+test_1() {
+    test_name='sample-test-app'
+    info "Starting tests for ${test_name}"
+
+    cid_file=$(mktemp -u --suffix=.cid)
+
+    # Since we built the candidate image locally, we don't want S2I attempt to pull
+    # it from Docker hub
+    s2i_args="--force-pull=false"
+
+    prepare
+    run_s2i_build $s2i_args
+    check_result $?
+
+    # Verify the 'usage' script is working properly when running the base image with 's2i usage ...'
+    test_s2i_usage
+    check_result $?
+
+    # Verify the 'usage' script is working properly when running the base image with 'docker run ...'
+    test_docker_run_usage
+    check_result $?
+
+    # Test application with default UID
+    test_application
+
+    # Test application with random UID
+    CONTAINER_ARGS="-u 12345" test_application
+
+    info "All tests for the ${test_name} finished successfully."
+    cleanup
+}
+test_1
+
+# Check scripts installed from CPAN are available to the application.
+test_2_function() {
+    test_response '/' 200 'Usage'
+}
+do_test 'binpath' 'test_2_function'
+
+# Check a single PSGI application is recognized a mod_perl is autoconfigured.
+test_3_function() {
+    test_response '/' 200 '<title>Web::Paste::Simple'
+}
+do_test 'psgi' 'test_3_function'
+
+# Check variables can select a PSGI application and set URI path.
+test_4_function() {
+    test_response '/path' 200 '<title>Web::Paste::Simple' && \
+    test_response '/cpanfile' 200 'requires'
+}
+do_test 'psgi-variables' 'test_4_function' 'PSGI_FILE=./application2.psgi,PSGI_URI_PATH=/path'
+
+# Check httpd access_log flows to stdout, error_log to stdout.
+# TODO: send error_log to stderr after dropping support for broken
+# docker < 1.9.
+test_5_function() {
+    test_response '/' 200 'Text in HTTP body' && \
+    test_stdout '"GET /[^"]*" 200 ' && \
+    test_stdout 'Warning on stderr'
+}
+do_test 'warningonstderr' 'test_5_function'
 
 info "All tests finished successfully."
